apiVersion: v1
kind: Pod
metadata:
  name: buggy-app
  labels:
    app: buggy-app
spec:
  containers:
  - name: java-leak-container
    image: eclipse-temurin:21-jre
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Starting memory leak simulation..."
        # -XX:+HeapDumpOnOutOfMemoryError: Tells JVM to dump heap on crash
        # -Xmx64m: Limits memory so it crashes quickly
        java -Xmx64m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/dump.hprof -version
        
        # Simulating a crash by exiting with an error code after some "work"
        sleep 5;
        echo "ERROR: java.lang.OutOfMemoryError: Java heap space" >&2
        exit 1
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"